export const GET_CONTINENT_DATA_START = "GET_CONTINENT_DATA_START";
export const GET_CONTINENT_DATA_SUCCESS = "GET_CONTINENT_DATA_SUCCESS";
export const GET_CONTINENT_DATA_FAILURE = "GET_CONTINENT_DATA_FAILURE";

export const GET_GLOBAL_STATS_START ="GET_GLOBAL_STATS_START"
export const GET_GLOBAL_STATS_SUCCESS ="GET_GLOBAL_STATS_SUCCESS"
export const GET_GLOBAL_STATS_FAILURE ="GET_GLOBAL_STATS_FAILURE"


export const GET_COUNTRY_HIST__DATA_START ="GET_COUNTRY_HIST__DATA_START"
export const GET_COUNTRY_HIST__DATA_SUCCESS ="GET_COUNTRY_HIST__DATA_SUCCESS"
export const GET_COUNTRY_HIST__DATA_FAILURE ="GET_COUNTRY_HIST__DATA_FAILURE"


export const GET_COUNTRY_DATA_START ="GET_COUNTRY_DATA_START"
export const GET_COUNTRY_DATA_SUCCESS ="GET_COUNTRY_DATA_SUCCESS"
export const GET_COUNTRY_DATA_FAILURE ="GET_COUNTRY_DATA_FAILURE"